### ISSUE TITLE
Save model after training

### ISSUE THREAD

**Issue by horenbergerb** [horenbergerb/BernoulliDiffusion#3]
The model filename should be added to the `config.yaml`. After training, the model should be saved to a file.

This is an easy one-liner that I will probably get around to doing soon.

**Comment by gokullan** [comment]
Hi, there! Can this issue be assigned to me?

**Comment by horenbergerb** [comment]
@gokullan sure, I've assigned it to you!

**Comment by horenbergerb** [comment]
Closing this case after merging a PR from @gokullan. Thanks for the help!
